---
- hosts: all
  tasks:
  - name: stop running container
    community.docker.docker_container:
      name: hello-world
      state: absent

  - name: pulling docker image
    community.docker.docker_image:
      name: proofofpizza/hello-world:latest
      source: pull

  - name: spin up container from image
    community.docker.docker_container:
      name: hello-world
      detach: yes
      published_ports: 8090:8080
      state: started
      image: proofofpizza/hello-world
